### ISSUE TITLE
Compare using and not using the gbwt

### ISSUE THREAD

**Issue by adamnovak** [vgteam/population-mapping-paper#1]
This is blocked on https://github.com/vgteam/toil-vg/issues/490

**Comment by ekg** [comment]
Could we call this "haplotype mapping paper"? We already map against a
population model.

**Comment by adamnovak** [comment]
Hm. That is true; the graph pangenome represents the population. Although I
guess we are testing the GBWT as a better population model, and even the
linear reference can be thought of as a bad population model.

Maybe we should call it "Population Haplotype Aware Mapping" (PHAM).

I will see about renaming everything.
